name: Build
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**/*.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          # required by release-tag.sh to correctly identify files changed in the last commit
          fetch-depth: 2
          # required by release-tag.sh to allow pushing with another credentials so other workflows are triggered
          persist-credentials: false
      - uses: actions/setup-java@v4.5.0
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Cache Gradle packages
        uses: actions/cache@v4.1.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        timeout-minutes: 25
        run: ./gradlew version
      - name: Release (if required)
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.ORG_PUBLIC_REPO_RELEASE_TRIGGERING }}@github.com/${GITHUB_REPOSITORY}.git
          ./release-tag.sh
        if: github.ref == 'refs/heads/master'
        env:
          GH_TOKEN: ${{ secrets.ORG_PUBLIC_REPO_RELEASE_TRIGGERING }}
