name: New Release - Update other projects
on:
  repository_dispatch:
    types: [http4k-platform-release]
jobs:
  create-upgrade-branches:
    strategy:
      matrix:
        repo:
          - 'http4k/examples'
          - 'http4k/http4k-bin'
          - 'http4k/http4k-by-example'
          - 'http4k/http4k-connect'
          - 'http4k/toolbox'
          - 'http4k/www'

          - 'http4k/lts-examples'
          - 'http4k/http4k-connect-examples'

    runs-on: ubuntu-latest
    steps:
      - name: Trigger ${{ matrix.repo }}
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          token: ${{ secrets.TOOLBOX_REPO_TOKEN }}
          repository: ${{ matrix.repo }}
#         TODO CHANGE THIS TO BE http4k-release
          event-type: http4k-platform-release
          client-payload: '{"version": "${{ github.event.client_payload.version }}"}'
