name: New Release - Slack
on:
  repository_dispatch:
    types: [http4k-release]
permissions:
  contents: read

jobs:
  slackify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: ./notify-slack.sh ${{ github.event.client_payload.version }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - run: ./notify-lts-slack.sh ${{ github.event.client_payload.version }}
        env:
          LTS_SLACK_WEBHOOK: ${{ secrets.LTS_SLACK_WEBHOOK }}
